# min-max-scaler: Examples to get a feeling for the code

In [40]:
import pandas as pd



from sklearn.preprocessing import MinMaxScaler

#Erklärung: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html This transformation is an alternative to zero mean, unit variance scaling.

#example for MinMaxScaler
df2 = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]] #4x2-metric. 1.Spalte: min=-1, range=2, 2.Spalte: min=2, range=16
df2=pd.DataFrame(df2, columns=['column1', 'column2'])
scaler = MinMaxScaler()
scaler.fit(df2)
#informationen über min-max-Scaler, der auf data trainiert wurde
print("feature minimum seen in the data:", scaler.data_min_) #minimum-werte
print("feature range (max-min) seen in the data:",scaler.data_range_) #Range-Werte 
print("Number of features seen during fit:", scaler.n_features_in_)
print("Names of features seen during fit (defined only when training-data has feature names that are all strings):", scaler.feature_names_in_)

#Ergebnis: transformieren von Werten
print("Transformation of df2:\n",scaler.transform(df2)) #Ergebnis: transformierung von df2
interest=pd.DataFrame([[2, 2]], columns=['column1', 'column2'])
print("Transformation of (2,2):",scaler.transform(interest)) #Ergebnis: transformierung von [2, 2]


feature minimum seen in the data: [-1.  2.]
feature range (max-min) seen in the data: [ 2. 16.]
Number of features seen during fit: 2
Names of features seen during fit (defined only when training-data has feature names that are all strings): ['column1' 'column2']
Transformation of df2:
 [[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]]
Transformation of (2,2): [[1.5 0. ]]


In [26]:
import pandas as pd

from sklearn.preprocessing import MinMaxScaler

#Erklärung: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html This transformation is an alternative to zero mean, unit variance scaling.

#example for MinMaxScaler
df2 = [[-1, 2,500], [-0.5, 6,700], [0, 10,500], [1, 18,600]] #4x2-metric. 1.Spalte: min=-1, länge=2, 2.Spalte: min=2, länge=16
df2=pd.DataFrame(df2, columns=['feature1', 'feature2', 'CarbonEmission'])
X_df2 = df2[['feature1', 'feature2']]
y_df2 = df2['CarbonEmission']
scaler = MinMaxScaler()
scaler.fit(X_df2,y_df2)

#informationen über min-max-Scaler, der auf data trainiert wurde
print("feature minimum seen in the data:", scaler.data_min_) #minimum-werte
print("feature range (max-min) seen in the data:",scaler.data_range_) #Range-Werte 
print("Number of features seen during fit:", scaler.n_features_in_)
print("Names of features seen during fit (defined only when training-data has feature names that are all strings):", scaler.feature_names_in_)

#Ergebnis: transformieren von Werten
print("Transformation of df2:\n",scaler.transform(X_df2)) #Ergebnis: transformierung von df2
interest=pd.DataFrame([[2, 2]], columns=['feature1', 'feature2'])
print("Transformation of (2,2):",scaler.transform(interest)) #Ergebnis: transformierung von [2, 2]

print("Undo the scaling of X:\n",scaler.inverse_transform([[0.,   0.  ],[0.25, 0.25],[0.5,  0.5 ],[1.,   1.  ]]))#ergibt df2[['column1', 'column2']]




feature minimum seen in the data: [-1.  2.]
feature range (max-min) seen in the data: [ 2. 16.]
Number of features seen during fit: 2
Names of features seen during fit (defined only when training-data has feature names that are all strings): ['feature1' 'feature2']
Transformation of df2:
 [[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]]
Transformation of (2,2): [[1.5 0. ]]
Undo the scaling of X:
 [[-1.   2. ]
 [-0.5  6. ]
 [ 0.  10. ]
 [ 1.  18. ]]


# min-max-scaler: in CarbonEmission-Project

In [41]:
import pandas as pd
import numpy as np
import seaborn as sns


df=pd.read_csv('Carbon_Emission.csv',sep=";")

#df = pd.read_csv('/kaggle/input/individual-carbon-footprint-calculation/Carbon Emission.csv')
#data can be found at https://www.kaggle.com/datasets/dumanmesut/individual-carbon-footprint-calculation/data


# change display settings to show all columns
pd.set_option('display.max_columns', None)


#rename
# rename columns: replace spaces with underscores
df.columns = df.columns.str.replace(' ', '_')
# Rename 'public' to 'public transport' and the car-typs - to make the information easier to understand
df['Vehicle_Type'] = df['Vehicle_Type'].replace({'public': 'public transport', 'petrol': 'car (type: petrol)','diesel': 'car (type: diesel)',
                                                'hybrid': 'car (type: hybrid)','lpg': 'car (type: lpg)','electric': 'car (type: electric)'})
df['Transport'] = df['Transport'].replace({'public': 'public transport', 'private': 'car'})


df.head()


Body_Type     Sex         Diet How_Often_Shower Heating_Energy_Source  \
0  overweight  female  pescatarian            daily                  coal   
1       obese  female   vegetarian  less frequently           natural gas   
2  overweight    male     omnivore  more frequently                  wood   
3  overweight    male     omnivore      twice a day                  wood   
4       obese  female   vegetarian            daily                  coal   

          Transport        Vehicle_Type Social_Activity  Monthly_Grocery_Bill  \
0  public transport                 NaN           often                   230   
1      walk/bicycle                 NaN           often                   114   
2               car  car (type: petrol)           never                   138   
3      walk/bicycle                 NaN       sometimes                   157   
4               car  car (type: diesel)           often                   266   

  Frequency_of_Traveling_by_Air  Vehicle_Monthly_Distance_Km Waste_Bag_Size  \
0                    frequently                          210          large   
1                        rarely                            9    extra large   
2                         never                         2472          small   
3                        rarely                           74         medium   
4               very frequently                         8457          large   

   Waste_Bag_Weekly_Count  How_Long_TV_PC_Daily_Hour  \
0                       4                          7   
1                       3                          9   
2                       1                         14   
3                       3                         20   
4                       1                          3   

   How_Many_New_Clothes_Monthly  How_Long_Internet_Daily_Hour  \
0                            26                             1   
1                            38                             5   
2                            47                             6   
3                             5                             7   
4                             5                             6   

  Energy_efficiency                               Recycling  \
0                No                               ['Metal']   
1                No                               ['Metal']   
2         Sometimes                               ['Metal']   
3         Sometimes  ['Paper', 'Plastic', 'Glass', 'Metal']   
4               Yes                               ['Paper']   

                         Cooking_With  CarbonEmission  
0                   ['Stove', 'Oven']            2238  
1              ['Stove', 'Microwave']            1892  
2               ['Oven', 'Microwave']            2595  
3  ['Microwave', 'Grill', 'Airfryer']            1074  
4                            ['Oven']            4743

In [42]:


variables_transport_vehicle_type=["Transport","Vehicle_Type"] 

variables_mit_mehreren_antwortmoeglichkeiten=["Recycling" ,"Cooking_With"]       

#variables_for_one_hot_encoded=df.select_dtypes(include=['object','category']).drop(['Transport','Vehicle_Type','Recycling','Cooking_With'],axis=1).columns.tolist()
#variables_for_one_hot_encoded=list(set(df.select_dtypes(include=['object','category']).columns.tolist()) - {'Transport','Vehicle Type','Recycling','Cooking_With'})
variables_for_one_hot_encoded=['Body_Type',
 'Sex',
 'Diet',
 'How_Often_Shower',
 'Heating_Energy_Source',
 'Social_Activity',
 'Frequency_of_Traveling_by_Air',
 'Waste_Bag_Size',
 'Energy_efficiency']


#variables that don't need processing, we can put them straight into our machine-learning-model
variables_quantitative =df.select_dtypes(include=[np.number]).drop('CarbonEmission',axis=1).columns.tolist()
#variables_quantitative = ["Monthly Grocery Bill", "Vehicle Monthly Distance Km","Waste Bag Weekly Count", "How Long TV PC Daily Hour","How Many New Clothes Monthly", "How Long Internet Daily Hour"]         

##############################################################################


from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

X = df[variables_quantitative + variables_for_one_hot_encoded]  
X

Monthly_Grocery_Bill  Vehicle_Monthly_Distance_Km  \
0                      230                          210   
1                      114                            9   
2                      138                         2472   
3                      157                           74   
4                      266                         8457   
...                    ...                          ...   
9995                   230                          268   
9996                   234                         5316   
9997                   298                           96   
9998                   179                         8688   
9999                   115                         9952   

      Waste_Bag_Weekly_Count  How_Long_TV_PC_Daily_Hour  \
0                          4                          7   
1                          3                          9   
2                          1                         14   
3                          3                         20   
4                          1                          3   
...                      ...                        ...   
9995                       5                         12   
9996                       3                         14   
9997                       5                         11   
9998                       5                         19   
9999                       4                         11   

      How_Many_New_Clothes_Monthly  How_Long_Internet_Daily_Hour    Body_Type  \
0                               26                             1   overweight   
1                               38                             5        obese   
2                               47                             6   overweight   
3                                5                             7   overweight   
4                                5                             6        obese   
...                            ...                           ...          ...   
9995                            27                             9        obese   
9996                             8                            24       normal   
9997                             5                            24   overweight   
9998                            14                             5  underweight   
9999                             6                             0        obese   

         Sex         Diet How_Often_Shower Heating_Energy_Source  \
0     female  pescatarian            daily                  coal   
1     female   vegetarian  less frequently           natural gas   
2       male     omnivore  more frequently                  wood   
3       male     omnivore      twice a day                  wood   
4     female   vegetarian            daily                  coal   
...      ...          ...              ...                   ...   
9995    male     omnivore      twice a day                  coal   
9996  female        vegan      twice a day                  coal   
9997  female   vegetarian            daily           electricity   
9998    male        vegan  more frequently                  coal   
9999    male  pescatarian      twice a day                  wood   

     Social_Activity Frequency_of_Traveling_by_Air Waste_Bag_Size  \
0              often                    frequently          large   
1              often                        rarely    extra large   
2              never                         never          small   
3          sometimes                        rarely         medium   
4              often               very frequently          large   
...              ...                           ...            ...   
9995       sometimes                         never         medium   
9996           never                    frequently    extra large   
9997       sometimes               very frequently    extra large   
9998           often                        rarely         medium   
9999       sometimes                   

In [43]:

##### one-hot-encoding ############################################

# Create the ColumnTransformer using the list "variables_for_one_hot_encoded"
cf = ColumnTransformer(
    [(col, OneHotEncoder(drop="first"), [col]) for col in variables_for_one_hot_encoded]+[(col, MinMaxScaler(), [col]) for col in variables_quantitative],  
    remainder="passthrough")

cf.fit(X)
cf

ColumnTransformer(remainder='passthrough',
                  transformers=[('Body_Type', OneHotEncoder(drop='first'),
                                 ['Body_Type']),
                                ('Sex', OneHotEncoder(drop='first'), ['Sex']),
                                ('Diet', OneHotEncoder(drop='first'), ['Diet']),
                                ('How_Often_Shower',
                                 OneHotEncoder(drop='first'),
                                 ['How_Often_Shower']),
                                ('Heating_Energy_Source',
                                 OneHotEncoder(drop='first'),
                                 ['Heating_Energy_Source']...
                                ('Vehicle_Monthly_Distance_Km', MinMaxScaler(),
                                 ['Vehicle_Monthly_Distance_Km']),
                                ('Waste_Bag_Weekly_Count', MinMaxScaler(),
                                 ['Waste_Bag_Weekly_Count']),
                                ('How_Long_TV_PC_Daily_Hour', MinMaxScaler(),
                                 ['How_Long_TV_PC_Daily_Hour']),
                                ('How_Many_New_Clothes_Monthly', MinMaxScaler(),
                                 ['How_Many_New_Clothes_Monthly']),
                                ('How_Long_Internet_Daily_Hour', MinMaxScaler(),
                                 ['How_Long_Internet_Daily_Hour'])])

In [30]:
X_transformed = cf.transform(X) # Data after scaling


##### scaling ############################################
# scaling so number are between 0 and 1

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

scaler.fit(X_transformed)
X_transformed_scaled = scaler.transform(X_transformed)  # Data after scaling

cf 

ColumnTransformer(remainder='passthrough',
                  transformers=[('Body_Type', OneHotEncoder(drop='first'),
                                 ['Body_Type']),
                                ('Sex', OneHotEncoder(drop='first'), ['Sex']),
                                ('Diet', OneHotEncoder(drop='first'), ['Diet']),
                                ('How_Often_Shower',
                                 OneHotEncoder(drop='first'),
                                 ['How_Often_Shower']),
                                ('Heating_Energy_Source',
                                 OneHotEncoder(drop='first'),
                                 ['Heating_Energy_Source']),
                                ('Social_Activity', OneHotEncoder(drop='first'),
                                 ['Social_Activity']),
                                ('Frequency_of_Traveling_by_Air',
                                 OneHotEncoder(drop='first'),
                                 ['Frequency_of_Traveling_by_Air']),
                                ('Waste_Bag_Size', OneHotEncoder(drop='first'),
                                 ['Waste_Bag_Size']),
                                ('Energy_efficiency',
                                 OneHotEncoder(drop='first'),
                                 ['Energy_efficiency'])])

[('Monthly_Grocery_Bill', MinMaxScaler(), ['Monthly_Grocery_Bill']),
 ('Vehicle_Monthly_Distance_Km',
  MinMaxScaler(),
  ['Vehicle_Monthly_Distance_Km']),
 ('Waste_Bag_Weekly_Count', MinMaxScaler(), ['Waste_Bag_Weekly_Count']),
 ('How_Long_TV_PC_Daily_Hour', MinMaxScaler(), ['How_Long_TV_PC_Daily_Hour']),
 ('How_Many_New_Clothes_Monthly',
  MinMaxScaler(),
  ['How_Many_New_Clothes_Monthly']),
 ('How_Long_Internet_Daily_Hour',
  MinMaxScaler(),
  ['How_Long_Internet_Daily_Hour'])]

# OneHotEncoder: Examples to get a feeling for the code

In [32]:
from sklearn.preprocessing import OneHotEncoder
oh = OneHotEncoder()
X = np.array([
["manuell"],
["automatik"],
["automatik"],
["manuell"],
["manuell"],
["automatik"]
])
oh.fit(X)
print(oh.categories_)
print(oh.transform(X).toarray())


[array(['automatik', 'manuell'], dtype='<U9')]
[[0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]]


# MulitLabelBinarizer: in CarbonEmission-Project

In [33]:
from sklearn.preprocessing import MultiLabelBinarizer
X=df[['Cooking_With']]
mlb = MultiLabelBinarizer()
mlb.fit_transform([X])

array([[1]])

In [34]:
mlb.classes_

array(['Cooking_With'], dtype=object)

In [35]:
mlb.fit_transform([{'sci-fi', 'thriller'}, {'comedy'}])
#array([[0, 1, 1],
#       [1, 0, 0]])


array([[0, 1, 1],
       [1, 0, 0]])

In [36]:
list(mlb.classes_)
#['comedy', 'sci-fi', 'thriller']

['comedy', 'sci-fi', 'thriller']